Upgrade toochain gcc from 6.3.0 to 6.4.0
This is mainly to address a failure to build from source with gcc 7 (which is
the default gcc on debian buster) unless -fpermissive is set. It turns out gcc
7's error here was very much a real mistake in gcc 6, which is why it got fixed
in 6.4.0. I'd guess there are other such cases that 6.4.0 addresses that I
didn't have the privilege to discover.

Thankfully the current 6.3.0 patches apply cleanly (with zero fuzz) on 6.4.0,
so this commit mainly just moves some names around.

The failure message in question:

g++ -fno-PIE -c   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I/home/gerow/repos/toaruos/toolchain/tarballs/gcc-6.3.0/gcc -I/home/gerow/repos/toaruos/toolchain/tarballs/gcc-6.3.0/gcc/. -I/home/gerow/repos/toaruos/toolchain/tarballs/gcc-6.3.0/gcc/../include -I/home/gerow/repos/toaruos/toolchain/tarballs/gcc-6.3.0/gcc/../libcpp/include  -I/home/gerow/repos/toaruos/toolchain/tarballs/gcc-6.3.0/gcc/../libdecnumber -I/home/gerow/repos/toaruos/toolchain/tarballs/gcc-6.3.0/gcc/../libdecnumber/dpd -I../libdecnumber -I/home/gerow/repos/toaruos/toolchain/tarballs/gcc-6.3.0/gcc/../libbacktrace   -o sanopt.o -MT sanopt.o -MMD -MP -MF ./.deps/sanopt.TPo /home/gerow/repos/toaruos/toolchain/tarballs/gcc-6.3.0/gcc/sanopt.c
/home/gerow/repos/toaruos/toolchain/tarballs/gcc-6.3.0/gcc/ubsan.c: In function ‘bool ubsan_use_new_style_p(location_t)’:
/home/gerow/repos/toaruos/toolchain/tarballs/gcc-6.3.0/gcc/ubsan.c:1474:23: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
       || xloc.file == '\0' || xloc.file[0] == '\xff'
                       ^~~~
Makefile:1085: recipe for target 'ubsan.o' failed
make[2]: *** [ubsan.o] Error 1