Disable size overrides in rme
(Fixes a warning that was caused by a "fix" to a undefined reference to
a missing 64-bit floating-point division function)